### ISSUE TITLE
there is some issue with the dependencies version . can you give a demo of how to run this

### ISSUE THREAD

**Issue by yash-2138** [HimanshuGupta-p1/Space_Share#5]

**Comment by yash-2138** [comment]
/home/ubuntu/Space_Share/space-share/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:138:10)
    at module.exports (/home/ubuntu/Space_Share/space-share/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/ubuntu/Space_Share/space-share/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/ubuntu/Space_Share/space-share/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/ubuntu/Space_Share/space-share/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/ubuntu/Space_Share/space-share/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/ubuntu/Space_Share/space-share/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/ubuntu/Space_Share/space-share/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/ubuntu/Space_Share/space-share/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v20.10.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by HimanshuGupta-p1** [comment]
> /home/ubuntu/Space_Share/space-share/node_modules/react-scripts/scripts/start.js:19 throw err; ^
> 
> Error: error:0308010C:digital envelope routines::unsupported at new Hash (node:internal/crypto/hash:68:19) at Object.createHash (node:crypto:138:10) at module.exports (/home/ubuntu/Space_Share/space-share/node_modules/webpack/lib/util/createHash.js:135:53) at NormalModule._initBuildHash (/home/ubuntu/Space_Share/space-share/node_modules/webpack/lib/NormalModule.js:417:16) at /home/ubuntu/Space_Share/space-share/node_modules/webpack/lib/NormalModule.js:452:10 at /home/ubuntu/Space_Share/space-share/node_modules/webpack/lib/NormalModule.js:323:13 at /home/ubuntu/Space_Share/space-share/node_modules/loader-runner/lib/LoaderRunner.js:367:11 at /home/ubuntu/Space_Share/space-share/node_modules/loader-runner/lib/LoaderRunner.js:233:18 at context.callback (/home/ubuntu/Space_Share/space-share/node_modules/loader-runner/lib/LoaderRunner.js:111:13) at /home/ubuntu/Space_Share/space-share/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 { opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ], library: 'digital envelope routines', reason: 'unsupported', code: 'ERR_OSSL_EVP_UNSUPPORTED' }
> 
> Node.js v20.10.0 error Command failed with exit code 1. info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Check this article regarding the issue that is coming, it is due to some local versions of Webpack.
https://stackoverflow.com/questions/69665222/node-js-17-0-1-gatsby-error-digital-envelope-routinesunsupported-err-os

**Comment by HimanshuGupta-p1** [comment]
I also fixed some dependency issues at my end.
